<?php
/**
 * V1beta1PodSecurityPolicySpecTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  CBSi\Kubernetes
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Kubernetes
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1.7.9
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace CBSi\Kubernetes;

/**
 * V1beta1PodSecurityPolicySpecTest Class Doc Comment
 *
 * @category    Class */
// * @description Pod Security Policy Spec defines the policy enforced.
/**
 * @package     CBSi\Kubernetes
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class V1beta1PodSecurityPolicySpecTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "V1beta1PodSecurityPolicySpec"
     */
    public function testV1beta1PodSecurityPolicySpec()
    {
    }

    /**
     * Test attribute "allowed_capabilities"
     */
    public function testPropertyAllowedCapabilities()
    {
    }

    /**
     * Test attribute "default_add_capabilities"
     */
    public function testPropertyDefaultAddCapabilities()
    {
    }

    /**
     * Test attribute "fs_group"
     */
    public function testPropertyFsGroup()
    {
    }

    /**
     * Test attribute "host_ipc"
     */
    public function testPropertyHostIpc()
    {
    }

    /**
     * Test attribute "host_network"
     */
    public function testPropertyHostNetwork()
    {
    }

    /**
     * Test attribute "host_pid"
     */
    public function testPropertyHostPid()
    {
    }

    /**
     * Test attribute "host_ports"
     */
    public function testPropertyHostPorts()
    {
    }

    /**
     * Test attribute "privileged"
     */
    public function testPropertyPrivileged()
    {
    }

    /**
     * Test attribute "read_only_root_filesystem"
     */
    public function testPropertyReadOnlyRootFilesystem()
    {
    }

    /**
     * Test attribute "required_drop_capabilities"
     */
    public function testPropertyRequiredDropCapabilities()
    {
    }

    /**
     * Test attribute "run_as_user"
     */
    public function testPropertyRunAsUser()
    {
    }

    /**
     * Test attribute "se_linux"
     */
    public function testPropertySeLinux()
    {
    }

    /**
     * Test attribute "supplemental_groups"
     */
    public function testPropertySupplementalGroups()
    {
    }

    /**
     * Test attribute "volumes"
     */
    public function testPropertyVolumes()
    {
    }
}
