<?php
/**
 * V1beta1APIServiceSpecTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  CBSi\Kubernetes
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Kubernetes
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1.7.9
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace CBSi\Kubernetes;

/**
 * V1beta1APIServiceSpecTest Class Doc Comment
 *
 * @category    Class */
// * @description APIServiceSpec contains information for locating and communicating with a server. Only https is supported, though you are able to disable certificate verification.
/**
 * @package     CBSi\Kubernetes
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class V1beta1APIServiceSpecTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "V1beta1APIServiceSpec"
     */
    public function testV1beta1APIServiceSpec()
    {
    }

    /**
     * Test attribute "ca_bundle"
     */
    public function testPropertyCaBundle()
    {
    }

    /**
     * Test attribute "group"
     */
    public function testPropertyGroup()
    {
    }

    /**
     * Test attribute "group_priority_minimum"
     */
    public function testPropertyGroupPriorityMinimum()
    {
    }

    /**
     * Test attribute "insecure_skip_tls_verify"
     */
    public function testPropertyInsecureSkipTlsVerify()
    {
    }

    /**
     * Test attribute "service"
     */
    public function testPropertyService()
    {
    }

    /**
     * Test attribute "version"
     */
    public function testPropertyVersion()
    {
    }

    /**
     * Test attribute "version_priority"
     */
    public function testPropertyVersionPriority()
    {
    }
}
