<?php
/**
 * V1ContainerStatusTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  CBSi\Kubernetes
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Kubernetes
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1.7.9
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace CBSi\Kubernetes;

/**
 * V1ContainerStatusTest Class Doc Comment
 *
 * @category    Class */
// * @description ContainerStatus contains details for the current status of this container.
/**
 * @package     CBSi\Kubernetes
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class V1ContainerStatusTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "V1ContainerStatus"
     */
    public function testV1ContainerStatus()
    {
    }

    /**
     * Test attribute "container_id"
     */
    public function testPropertyContainerId()
    {
    }

    /**
     * Test attribute "image"
     */
    public function testPropertyImage()
    {
    }

    /**
     * Test attribute "image_id"
     */
    public function testPropertyImageId()
    {
    }

    /**
     * Test attribute "last_state"
     */
    public function testPropertyLastState()
    {
    }

    /**
     * Test attribute "name"
     */
    public function testPropertyName()
    {
    }

    /**
     * Test attribute "ready"
     */
    public function testPropertyReady()
    {
    }

    /**
     * Test attribute "restart_count"
     */
    public function testPropertyRestartCount()
    {
    }

    /**
     * Test attribute "state"
     */
    public function testPropertyState()
    {
    }
}
