<?php
/**
 * V1HorizontalPodAutoscalerSpecTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  CBSi\Kubernetes
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Kubernetes
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1.7.9
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace CBSi\Kubernetes;

/**
 * V1HorizontalPodAutoscalerSpecTest Class Doc Comment
 *
 * @category    Class */
// * @description specification of a horizontal pod autoscaler.
/**
 * @package     CBSi\Kubernetes
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class V1HorizontalPodAutoscalerSpecTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "V1HorizontalPodAutoscalerSpec"
     */
    public function testV1HorizontalPodAutoscalerSpec()
    {
    }

    /**
     * Test attribute "max_replicas"
     */
    public function testPropertyMaxReplicas()
    {
    }

    /**
     * Test attribute "min_replicas"
     */
    public function testPropertyMinReplicas()
    {
    }

    /**
     * Test attribute "scale_target_ref"
     */
    public function testPropertyScaleTargetRef()
    {
    }

    /**
     * Test attribute "target_cpu_utilization_percentage"
     */
    public function testPropertyTargetCpuUtilizationPercentage()
    {
    }
}
