<?php
/**
 * V1LimitRangeItemTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  CBSi\Kubernetes
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Kubernetes
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1.7.9
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace CBSi\Kubernetes;

/**
 * V1LimitRangeItemTest Class Doc Comment
 *
 * @category    Class */
// * @description LimitRangeItem defines a min/max usage limit for any resource that matches on kind.
/**
 * @package     CBSi\Kubernetes
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class V1LimitRangeItemTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "V1LimitRangeItem"
     */
    public function testV1LimitRangeItem()
    {
    }

    /**
     * Test attribute "default"
     */
    public function testPropertyDefault()
    {
    }

    /**
     * Test attribute "default_request"
     */
    public function testPropertyDefaultRequest()
    {
    }

    /**
     * Test attribute "max"
     */
    public function testPropertyMax()
    {
    }

    /**
     * Test attribute "max_limit_request_ratio"
     */
    public function testPropertyMaxLimitRequestRatio()
    {
    }

    /**
     * Test attribute "min"
     */
    public function testPropertyMin()
    {
    }

    /**
     * Test attribute "type"
     */
    public function testPropertyType()
    {
    }
}
