<?php
/**
 * V1PodStatusTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  CBSi\Kubernetes
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Kubernetes
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1.7.9
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace CBSi\Kubernetes;

/**
 * V1PodStatusTest Class Doc Comment
 *
 * @category    Class */
// * @description PodStatus represents information about the status of a pod. Status may trail the actual state of a system.
/**
 * @package     CBSi\Kubernetes
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class V1PodStatusTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "V1PodStatus"
     */
    public function testV1PodStatus()
    {
    }

    /**
     * Test attribute "conditions"
     */
    public function testPropertyConditions()
    {
    }

    /**
     * Test attribute "container_statuses"
     */
    public function testPropertyContainerStatuses()
    {
    }

    /**
     * Test attribute "host_ip"
     */
    public function testPropertyHostIp()
    {
    }

    /**
     * Test attribute "init_container_statuses"
     */
    public function testPropertyInitContainerStatuses()
    {
    }

    /**
     * Test attribute "message"
     */
    public function testPropertyMessage()
    {
    }

    /**
     * Test attribute "phase"
     */
    public function testPropertyPhase()
    {
    }

    /**
     * Test attribute "pod_ip"
     */
    public function testPropertyPodIp()
    {
    }

    /**
     * Test attribute "qos_class"
     */
    public function testPropertyQosClass()
    {
    }

    /**
     * Test attribute "reason"
     */
    public function testPropertyReason()
    {
    }

    /**
     * Test attribute "start_time"
     */
    public function testPropertyStartTime()
    {
    }
}
