<?php
/**
 * V1PortworxVolumeSourceTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  CBSi\Kubernetes
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Kubernetes
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1.7.9
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace CBSi\Kubernetes;

/**
 * V1PortworxVolumeSourceTest Class Doc Comment
 *
 * @category    Class */
// * @description PortworxVolumeSource represents a Portworx volume resource.
/**
 * @package     CBSi\Kubernetes
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class V1PortworxVolumeSourceTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "V1PortworxVolumeSource"
     */
    public function testV1PortworxVolumeSource()
    {
    }

    /**
     * Test attribute "fs_type"
     */
    public function testPropertyFsType()
    {
    }

    /**
     * Test attribute "read_only"
     */
    public function testPropertyReadOnly()
    {
    }

    /**
     * Test attribute "volume_id"
     */
    public function testPropertyVolumeId()
    {
    }
}
