<?php
/**
 * V1ServiceAccountTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  CBSi\Kubernetes
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Kubernetes
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1.7.9
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace CBSi\Kubernetes;

/**
 * V1ServiceAccountTest Class Doc Comment
 *
 * @category    Class */
// * @description ServiceAccount binds together: * a name, understood by users, and perhaps by peripheral systems, for an identity * a principal that can be authenticated and authorized * a set of secrets
/**
 * @package     CBSi\Kubernetes
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class V1ServiceAccountTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "V1ServiceAccount"
     */
    public function testV1ServiceAccount()
    {
    }

    /**
     * Test attribute "api_version"
     */
    public function testPropertyApiVersion()
    {
    }

    /**
     * Test attribute "automount_service_account_token"
     */
    public function testPropertyAutomountServiceAccountToken()
    {
    }

    /**
     * Test attribute "image_pull_secrets"
     */
    public function testPropertyImagePullSecrets()
    {
    }

    /**
     * Test attribute "kind"
     */
    public function testPropertyKind()
    {
    }

    /**
     * Test attribute "metadata"
     */
    public function testPropertyMetadata()
    {
    }

    /**
     * Test attribute "secrets"
     */
    public function testPropertySecrets()
    {
    }
}
