<?php
/**
 * BatchV1ApiTest
 * PHP version 5
 *
 * @category Class
 * @package  CBSi\Kubernetes
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Kubernetes
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1.7.9
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace CBSi\Kubernetes;

use \CBSi\Kubernetes\Configuration;
use \CBSi\Kubernetes\ApiException;
use \CBSi\Kubernetes\ObjectSerializer;

/**
 * BatchV1ApiTest Class Doc Comment
 *
 * @category Class
 * @package  CBSi\Kubernetes
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class BatchV1ApiTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test case for createNamespacedJob
     *
     * .
     *
     */
    public function testCreateNamespacedJob()
    {
    }

    /**
     * Test case for deleteCollectionNamespacedJob
     *
     * .
     *
     */
    public function testDeleteCollectionNamespacedJob()
    {
    }

    /**
     * Test case for deleteNamespacedJob
     *
     * .
     *
     */
    public function testDeleteNamespacedJob()
    {
    }

    /**
     * Test case for getAPIResources
     *
     * .
     *
     */
    public function testGetAPIResources()
    {
    }

    /**
     * Test case for listJobForAllNamespaces
     *
     * .
     *
     */
    public function testListJobForAllNamespaces()
    {
    }

    /**
     * Test case for listNamespacedJob
     *
     * .
     *
     */
    public function testListNamespacedJob()
    {
    }

    /**
     * Test case for patchNamespacedJob
     *
     * .
     *
     */
    public function testPatchNamespacedJob()
    {
    }

    /**
     * Test case for patchNamespacedJobStatus
     *
     * .
     *
     */
    public function testPatchNamespacedJobStatus()
    {
    }

    /**
     * Test case for readNamespacedJob
     *
     * .
     *
     */
    public function testReadNamespacedJob()
    {
    }

    /**
     * Test case for readNamespacedJobStatus
     *
     * .
     *
     */
    public function testReadNamespacedJobStatus()
    {
    }

    /**
     * Test case for replaceNamespacedJob
     *
     * .
     *
     */
    public function testReplaceNamespacedJob()
    {
    }

    /**
     * Test case for replaceNamespacedJobStatus
     *
     * .
     *
     */
    public function testReplaceNamespacedJobStatus()
    {
    }
}
