<?php
/**
 * CertificatesV1beta1ApiTest
 * PHP version 5
 *
 * @category Class
 * @package  CBSi\Kubernetes
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Kubernetes
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1.7.9
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace CBSi\Kubernetes;

use \CBSi\Kubernetes\Configuration;
use \CBSi\Kubernetes\ApiException;
use \CBSi\Kubernetes\ObjectSerializer;

/**
 * CertificatesV1beta1ApiTest Class Doc Comment
 *
 * @category Class
 * @package  CBSi\Kubernetes
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class CertificatesV1beta1ApiTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test case for createCertificateSigningRequest
     *
     * .
     *
     */
    public function testCreateCertificateSigningRequest()
    {
    }

    /**
     * Test case for deleteCertificateSigningRequest
     *
     * .
     *
     */
    public function testDeleteCertificateSigningRequest()
    {
    }

    /**
     * Test case for deleteCollectionCertificateSigningRequest
     *
     * .
     *
     */
    public function testDeleteCollectionCertificateSigningRequest()
    {
    }

    /**
     * Test case for getAPIResources
     *
     * .
     *
     */
    public function testGetAPIResources()
    {
    }

    /**
     * Test case for listCertificateSigningRequest
     *
     * .
     *
     */
    public function testListCertificateSigningRequest()
    {
    }

    /**
     * Test case for patchCertificateSigningRequest
     *
     * .
     *
     */
    public function testPatchCertificateSigningRequest()
    {
    }

    /**
     * Test case for readCertificateSigningRequest
     *
     * .
     *
     */
    public function testReadCertificateSigningRequest()
    {
    }

    /**
     * Test case for replaceCertificateSigningRequest
     *
     * .
     *
     */
    public function testReplaceCertificateSigningRequest()
    {
    }

    /**
     * Test case for replaceCertificateSigningRequestApproval
     *
     * .
     *
     */
    public function testReplaceCertificateSigningRequestApproval()
    {
    }

    /**
     * Test case for replaceCertificateSigningRequestStatus
     *
     * .
     *
     */
    public function testReplaceCertificateSigningRequestStatus()
    {
    }
}
