<?php
/**
 * CustomObjectsApiTest
 * PHP version 5
 *
 * @category Class
 * @package  CBSi\Kubernetes
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Kubernetes
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1.7.9
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace CBSi\Kubernetes;

use \CBSi\Kubernetes\Configuration;
use \CBSi\Kubernetes\ApiException;
use \CBSi\Kubernetes\ObjectSerializer;

/**
 * CustomObjectsApiTest Class Doc Comment
 *
 * @category Class
 * @package  CBSi\Kubernetes
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class CustomObjectsApiTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test case for createClusterCustomObject
     *
     * .
     *
     */
    public function testCreateClusterCustomObject()
    {
    }

    /**
     * Test case for createNamespacedCustomObject
     *
     * .
     *
     */
    public function testCreateNamespacedCustomObject()
    {
    }

    /**
     * Test case for deleteClusterCustomObject
     *
     * .
     *
     */
    public function testDeleteClusterCustomObject()
    {
    }

    /**
     * Test case for deleteNamespacedCustomObject
     *
     * .
     *
     */
    public function testDeleteNamespacedCustomObject()
    {
    }

    /**
     * Test case for getClusterCustomObject
     *
     * .
     *
     */
    public function testGetClusterCustomObject()
    {
    }

    /**
     * Test case for getNamespacedCustomObject
     *
     * .
     *
     */
    public function testGetNamespacedCustomObject()
    {
    }

    /**
     * Test case for listClusterCustomObject
     *
     * .
     *
     */
    public function testListClusterCustomObject()
    {
    }

    /**
     * Test case for listNamespacedCustomObject
     *
     * .
     *
     */
    public function testListNamespacedCustomObject()
    {
    }

    /**
     * Test case for replaceClusterCustomObject
     *
     * .
     *
     */
    public function testReplaceClusterCustomObject()
    {
    }

    /**
     * Test case for replaceNamespacedCustomObject
     *
     * .
     *
     */
    public function testReplaceNamespacedCustomObject()
    {
    }
}
