<?php
/**
 * PolicyV1beta1ApiTest
 * PHP version 5
 *
 * @category Class
 * @package  CBSi\Kubernetes
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Kubernetes
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1.7.9
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace CBSi\Kubernetes;

use \CBSi\Kubernetes\Configuration;
use \CBSi\Kubernetes\ApiException;
use \CBSi\Kubernetes\ObjectSerializer;

/**
 * PolicyV1beta1ApiTest Class Doc Comment
 *
 * @category Class
 * @package  CBSi\Kubernetes
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class PolicyV1beta1ApiTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test case for createNamespacedPodDisruptionBudget
     *
     * .
     *
     */
    public function testCreateNamespacedPodDisruptionBudget()
    {
    }

    /**
     * Test case for deleteCollectionNamespacedPodDisruptionBudget
     *
     * .
     *
     */
    public function testDeleteCollectionNamespacedPodDisruptionBudget()
    {
    }

    /**
     * Test case for deleteNamespacedPodDisruptionBudget
     *
     * .
     *
     */
    public function testDeleteNamespacedPodDisruptionBudget()
    {
    }

    /**
     * Test case for getAPIResources
     *
     * .
     *
     */
    public function testGetAPIResources()
    {
    }

    /**
     * Test case for listNamespacedPodDisruptionBudget
     *
     * .
     *
     */
    public function testListNamespacedPodDisruptionBudget()
    {
    }

    /**
     * Test case for listPodDisruptionBudgetForAllNamespaces
     *
     * .
     *
     */
    public function testListPodDisruptionBudgetForAllNamespaces()
    {
    }

    /**
     * Test case for patchNamespacedPodDisruptionBudget
     *
     * .
     *
     */
    public function testPatchNamespacedPodDisruptionBudget()
    {
    }

    /**
     * Test case for patchNamespacedPodDisruptionBudgetStatus
     *
     * .
     *
     */
    public function testPatchNamespacedPodDisruptionBudgetStatus()
    {
    }

    /**
     * Test case for readNamespacedPodDisruptionBudget
     *
     * .
     *
     */
    public function testReadNamespacedPodDisruptionBudget()
    {
    }

    /**
     * Test case for readNamespacedPodDisruptionBudgetStatus
     *
     * .
     *
     */
    public function testReadNamespacedPodDisruptionBudgetStatus()
    {
    }

    /**
     * Test case for replaceNamespacedPodDisruptionBudget
     *
     * .
     *
     */
    public function testReplaceNamespacedPodDisruptionBudget()
    {
    }

    /**
     * Test case for replaceNamespacedPodDisruptionBudgetStatus
     *
     * .
     *
     */
    public function testReplaceNamespacedPodDisruptionBudgetStatus()
    {
    }
}
