<?php
/**
 * RbacAuthorizationV1beta1ApiTest
 * PHP version 5
 *
 * @category Class
 * @package  CBSi\Kubernetes
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Kubernetes
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1.7.9
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace CBSi\Kubernetes;

use \CBSi\Kubernetes\Configuration;
use \CBSi\Kubernetes\ApiException;
use \CBSi\Kubernetes\ObjectSerializer;

/**
 * RbacAuthorizationV1beta1ApiTest Class Doc Comment
 *
 * @category Class
 * @package  CBSi\Kubernetes
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class RbacAuthorizationV1beta1ApiTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test case for createClusterRole
     *
     * .
     *
     */
    public function testCreateClusterRole()
    {
    }

    /**
     * Test case for createClusterRoleBinding
     *
     * .
     *
     */
    public function testCreateClusterRoleBinding()
    {
    }

    /**
     * Test case for createNamespacedRole
     *
     * .
     *
     */
    public function testCreateNamespacedRole()
    {
    }

    /**
     * Test case for createNamespacedRoleBinding
     *
     * .
     *
     */
    public function testCreateNamespacedRoleBinding()
    {
    }

    /**
     * Test case for deleteClusterRole
     *
     * .
     *
     */
    public function testDeleteClusterRole()
    {
    }

    /**
     * Test case for deleteClusterRoleBinding
     *
     * .
     *
     */
    public function testDeleteClusterRoleBinding()
    {
    }

    /**
     * Test case for deleteCollectionClusterRole
     *
     * .
     *
     */
    public function testDeleteCollectionClusterRole()
    {
    }

    /**
     * Test case for deleteCollectionClusterRoleBinding
     *
     * .
     *
     */
    public function testDeleteCollectionClusterRoleBinding()
    {
    }

    /**
     * Test case for deleteCollectionNamespacedRole
     *
     * .
     *
     */
    public function testDeleteCollectionNamespacedRole()
    {
    }

    /**
     * Test case for deleteCollectionNamespacedRoleBinding
     *
     * .
     *
     */
    public function testDeleteCollectionNamespacedRoleBinding()
    {
    }

    /**
     * Test case for deleteNamespacedRole
     *
     * .
     *
     */
    public function testDeleteNamespacedRole()
    {
    }

    /**
     * Test case for deleteNamespacedRoleBinding
     *
     * .
     *
     */
    public function testDeleteNamespacedRoleBinding()
    {
    }

    /**
     * Test case for getAPIResources
     *
     * .
     *
     */
    public function testGetAPIResources()
    {
    }

    /**
     * Test case for listClusterRole
     *
     * .
     *
     */
    public function testListClusterRole()
    {
    }

    /**
     * Test case for listClusterRoleBinding
     *
     * .
     *
     */
    public function testListClusterRoleBinding()
    {
    }

    /**
     * Test case for listNamespacedRole
     *
     * .
     *
     */
    public function testListNamespacedRole()
    {
    }

    /**
     * Test case for listNamespacedRoleBinding
     *
     * .
     *
     */
    public function testListNamespacedRoleBinding()
    {
    }

    /**
     * Test case for listRoleBindingForAllNamespaces
     *
     * .
     *
     */
    public function testListRoleBindingForAllNamespaces()
    {
    }

    /**
     * Test case for listRoleForAllNamespaces
     *
     * .
     *
     */
    public function testListRoleForAllNamespaces()
    {
    }

    /**
     * Test case for patchClusterRole
     *
     * .
     *
     */
    public function testPatchClusterRole()
    {
    }

    /**
     * Test case for patchClusterRoleBinding
     *
     * .
     *
     */
    public function testPatchClusterRoleBinding()
    {
    }

    /**
     * Test case for patchNamespacedRole
     *
     * .
     *
     */
    public function testPatchNamespacedRole()
    {
    }

    /**
     * Test case for patchNamespacedRoleBinding
     *
     * .
     *
     */
    public function testPatchNamespacedRoleBinding()
    {
    }

    /**
     * Test case for readClusterRole
     *
     * .
     *
     */
    public function testReadClusterRole()
    {
    }

    /**
     * Test case for readClusterRoleBinding
     *
     * .
     *
     */
    public function testReadClusterRoleBinding()
    {
    }

    /**
     * Test case for readNamespacedRole
     *
     * .
     *
     */
    public function testReadNamespacedRole()
    {
    }

    /**
     * Test case for readNamespacedRoleBinding
     *
     * .
     *
     */
    public function testReadNamespacedRoleBinding()
    {
    }

    /**
     * Test case for replaceClusterRole
     *
     * .
     *
     */
    public function testReplaceClusterRole()
    {
    }

    /**
     * Test case for replaceClusterRoleBinding
     *
     * .
     *
     */
    public function testReplaceClusterRoleBinding()
    {
    }

    /**
     * Test case for replaceNamespacedRole
     *
     * .
     *
     */
    public function testReplaceNamespacedRole()
    {
    }

    /**
     * Test case for replaceNamespacedRoleBinding
     *
     * .
     *
     */
    public function testReplaceNamespacedRoleBinding()
    {
    }
}
